# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='public.Course'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='content',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
